[package]
name = "umc_qmc"
version = "0.1.6"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
byteorder = "1.5.0"
itertools = "0.13.0"
lazy_static = "1.5.0"
tc_tea = { version = "0.2.1", default-features = false }
thiserror = "2.0.7"
umc_utils = { path = "../utils" }
